name: Merchsloth Post Reminder

on:
  workflow_dispatch:

jobs:
  check-post-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Check latest post date
        id: check-date
        run: python merchsloth/check_post.py

      - name: Notify failure
        if: failure()
        run: echo "Action failed because no post was made for today."
